# Model settings
model:
  name: "gpt-4o"

# Dataset settings
n_samples:
  train: 512
  test: 100

# Few-shot learning settings
few_shot:
  n_shots_list: [0, 1, 2, 4, 8, 16, 32, 64, 128, 256, 512]

# File paths
paths:
  train_dir: "data/raw/train"
  test_dir: "data/raw/test"
  processed_dir: "data/processed/"
  figures_dir: "figures"
