# Model settings
model:
  name: "gpt-4o"
  temperature: 0

# Dataset settings
n_samples:
  train: 100
  test: 50

# Few-shot learning settings
few_shot:
  n_shots_list: [0, 4, 8, 16, 32, 64, 100]

# File paths
paths:
  train_dir: "data/raw/train"
  test_dir: "data/raw/test"
  responses_dir: "data/processed/responses"
  figures_dir: "figures"
