# Model settings
model:
  name: "gpt-4o"

# Dataset settings
n_samples:
  train: 1024
  test: 100

# Few-shot learning settings
few_shot:
  n_shots_list: [512]

# File paths
paths:
  train_dir: "data/raw/train"
  test_dir: "data/raw/test"
  responses_dir: "data/processed/responses"
  figures_dir: "figures"
