# Model settings
model:
  name: "gpt-4o-mini"

# Dataset settings
n_samples:
  train: 10
  test: 10

# Few-shot learning settings
few_shot:
  n_shots_list: [0, 4]

# File paths
paths:
  train_dir: "data/raw/train"
  test_dir: "data/raw/test"
  processed_dir: "data/processed/"
  figures_dir: "figures"
