# Model settings
model:
  name: "gpt-4o"

# Dataset settings
n_samples:
  train: 100
  test: 50

# Few-shot learning settings
few_shot:
  n_shots_list: [0, 8, 16, 32, 64]

# File paths
paths:
  train_dir: "data/raw/train"
  test_dir: "data/raw/test"
  processed_dir: "data/processed/"
  figures_dir: "figures"
